name: Azure Static Web App CI/CD
on:
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy to Azure Static Web App
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_BAY_0D02DB810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "/"
          api_location: ""
          app_artifact_location: "dist"
          output_location: "" # if you want to specify a different location for the static content
          action: "upload"
          deployment_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_BAY_0D02DB810 }}
